### ISSUE TITLE
簡単なAPIドキュメントを作成

### ISSUE THREAD

**Issue by kfukazawa-cq** [auglish-cq/book_manager_server#5]
以下のことを記載
- Endpoint一覧
- 必須・オプションパラメータ

本当に簡単でいいのですが、あると便利です。

**Comment by kfukazawa-cq** [comment]
@auglish-cq 
簡単に作成しました。
ほとんど変わることないと思うので、自動生成とかはしないです。

https://github.com/auglish-cq/book_manager_server/wiki/api_docs

**Comment by kfukazawa-cq** [comment]
@auglish-cq 
お手隙で上記確認お願いします。
作成したDocとエラーメッセージが適切に返って来れば必要情報は足りると思います:bow:

**Comment by auglish-cq** [comment]
@kfukazawa-cq 作成ありがとうございます！！！
確認します。
